apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  namespace: flexcub-testing
status:
  loadBalancer: {}
spec:
  ports:
    - name: eureka-svc
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: eureka
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster